### ISSUE TITLE
Panel Variables Sync: Prompt user for a list of panels to associate variables to.

### ISSUE THREAD

**Issue by josh-silvas** [nautobot/nautobot-plugin-chatops-grafana#12]
### Proposed Functionality
Currently, the panel variables sync will create and associate a panel variable for each panel in the dashboard.  The proposed functionality would also prompt the user with a list of panels in the dashboard to create variables for, rather than all panels.

**Comment by davidban77** [comment]
This will be reviewed in 2.0
